name: CoderCo Combined

on:
  push:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Select Python version"
        required: true
        default: "3.10"
        type: choice
        options:
          - '3.10'
          - '3.12'
          - '3.13'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python-version }}

      - name: install dependencies
        run: |
          cd chapter4
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run tests
        run: |
          cd chapter4
          python -m unittest discover

      - name: notify us of success
        if: success()
        run: echo "Tests passed on Python ${{ github.event.inputs.python-version }}"


